# ==========================
# Theme Settings
# ==========================

# Gemfile ì— minimal-mistakes-jekyll ì´ ë“¤ì–´ìˆìœ¼ë¯€ë¡œ theme ë°©ì‹ ì‚¬ìš©
#theme                  : "minimal-mistakes-jekyll"
remote_theme         : "mmistakes/minimal-mistakes"  # GitHub Pagesì—ì„œ remote_theme ì“¸ ë•Œ ì‚¬ìš©
minimal_mistakes_skin  : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# ==========================
# Site Settings
# ==========================

locale                 : "en"      # ì‚¬ì´íŠ¸ ê¸°ë³¸ ì–¸ì–´
title                  : "Joseph Lee Blog"
title_separator        : "-"
# subtitle               : "Cloud Â· M365 Â· Notes"
name                   : "Joseph Lee"
description            : "Engineering Blog by Joseph Lee"
url                    : "https://eelhpesoj.github.io"   # Josephë‹˜ GitHub Pages ë„ë©”ì¸
baseurl                : ""                              # ì‚¬ìš©ì í˜ì´ì§€ë©´ ë¹ˆ ê°’
repository             : "eelhpesoj/eelhpesoj.github.io"   # GitHub username/repo-name
teaser                 : # "/assets/images/500x300.png"
logo                   : # "/assets/images/logo.png"
masthead_title         : ""    # ìƒë‹¨ ì¢Œì¸¡ì— ë³´ì¼ íƒ€ì´í‹€ (ê³µë°± " "ì´ë©´ í‘œì‹œ ì•ˆ í•¨)
breadcrumbs            : true          # í˜ì´ì§€ ìƒë‹¨ì— breadcrumb ì‚¬ìš©
words_per_minute       : 200
enable_copy_code_button: true          # ì½”ë“œë¸”ë¡ ë³µì‚¬ ë²„íŠ¼

copyright              : "Joseph Lee"
copyright_url          : "https://eelhpesoj.github.io"

comments:
  provider             : "utterances"
  utterances:
    repo                : "eelhpesoj/eelhpesoj.github.io"
    issue_term         : "pathname"
    label              : "ğŸ’¬ comment"
    theme              : "github-light"
  

atom_feed:
  path                 : # ê¸°ë³¸ê°’ ì‚¬ìš©
  hide                 : false

search                 : true          # ìƒë‹¨ ê²€ìƒ‰ ì¼œê¸°
search_full_content    : false
search_provider        : lunr
lunr:
  search_within_pages  : true

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# ==========================
# Social Sharing / Profiles
# ==========================

twitter:
  username             :
facebook:
  username             :
  app_id               :
  publisher            :
og_image               :

social:
  type                 : "Person"
  name                 : "Joseph Lee"
  links:
    - "https://github.com/eelhpesoj/eelhpesoj.github.io"
    # í•„ìš”í•˜ë©´ LinkedIn, Blog ë“± ì¶”ê°€

# ==========================
# Analytics
# ==========================

analytics:
  provider             : false
  google:
    tracking_id        :
    anonymize_ip       :

# ==========================
# Site Author
# ==========================

author:
  name           : "Joseph Lee"
  avatar         : "favicon/favicon-96x96.png"
  bio            : "A full-stack engineering mindset"
  location       : "Seoul, Korea"
  email          : #"leeyosebi@gmail.com"

  links:
    - label      : "GitHub"
      icon       : "fab fa-fw fa-github"
      url        : "https://github.com/eelhpesoj/eelhpesoj.github.io"

    - label      : "LinkedIn"
      icon       : "fab fa-fw fa-linkedin"
      url        : "https://www.linkedin.com/in/joseph-lee-870660260/"

    - label      : "Contact Me: Joseph Lee"
      icon       : "fas fa-fw fa-envelope"
      url        : "mailto:leeyosebi@gmail.com"

    - label      : "Request Us: Engineering team"
      icon       : "fas fa-fw fa-envelope"
      url        : "mailto:dobineer@gmail.com"

    # í•„ìš”í•˜ë©´ Email, X, LinkedIn ë“± ì¶”ê°€

# ==========================
# Site Footer
# ==========================




# ==========================
# Reading Files
# ==========================

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# ==========================
# Conversion
# ==========================

markdown           : kramdown
highlighter        : rouge
lsi                : false
excerpt_separator  : "\n\n"
incremental        : false

kramdown:
  input            : GFM
  hard_wrap        : false
  auto_ids         : true
  footnote_nr      : 1
  entity_output    : as_char
  toc_levels       : 1..6
  smart_quotes     : lsquo,rsquo,ldquo,rdquo
  enable_coderay   : false

# ==========================
# Sass/SCSS
# ==========================

sass:
  sass_dir         : _sass
  style            : compressed

# ==========================
# Outputting
# ==========================

permalink          : /:categories/:title/
timezone           : "Asia/Seoul"

# ==========================
# Pagination
# ==========================

paginate           : 5
paginate_path      : /page:num/

pagination:
  debug            : false
  collection       : 'posts'
  per_page         : 10
  permalink        : '/page/:num/'
  title            : ':title - page :num'
  limit            : 0
  sort_field       : 'date'
  sort_reverse     : true
  category         : 'posts'
  tag              : ''
  locale           : ''
  trail:
    before         : 2
    after          : 2

# ==========================
# Plugins
# ==========================

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# ==========================
# Archives
# ==========================

category_archive:
  type             : liquid
  path             : /categories/
tag_archive:
  type             : liquid
  path             : /tags/

# ==========================
# HTML Compression
# ==========================

compress_html:
  clippings        : all
  ignore:
    envs           : development

# ==========================
# Defaults
# ==========================

defaults:
  - scope:
      path         : ""
      type         : posts
    values:
      layout       : single
      author_profile : true
      read_time    : true
      comments     : true
      share        : #true
      related      : true
      toc: true
      toc_label: "On this page"
      toc_sticky: true
      toc_icon: "list"